version: "3.9"
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
    volumes:
      - "./server:/server"
      - /server/node_modules
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API=http://localhost:4000/task
    volumes:
      - "./client:/client"
      - "/client/node_modules"
    depends_on:
      - "server"
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
    volumes:
      - "./worker:/worker"
      - "/worker/node_modules"
    depends_on:
      - "server"