name: Deploy Worker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "online-ide-worker"
          heroku_email: ${{secrets.EMAIL}}
          appdir: "worker"
          stack: "container"
          usedocker: true
